account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as authViews
from django.urls import reverse_lazy
from .forms import PasswordFormUpdate, UserFormLogin, PasswordSetForm

app_name = 'account'

urlpatterns = [
    path('login/', authViews.LoginView.as_view(template_name="pages/login.html",form_class=UserFormLogin,redirect_authenticated_user=True,success_url = reverse_lazy("account:account")),name = 'login'),
    path('sign-up/', views.SignUpView.as_view(),name = 'signUp'),
    path('logout/', views.Logout.as_view(),name = 'logout'),
    path('account/', views.AccountView.as_view(),name = 'account'),
    path('update-user/', views.UpdateUserView,name="updateUser"),
    path("password_reset/", authViews.PasswordResetView.as_view(template_name="pages/passwordReset.html",email_template_name="pages/emailSend.html", success_url = reverse_lazy("account:password_reset_done")), name="password_reset"),
    path("password_reset/done/",authViews.PasswordResetDoneView.as_view(template_name="pages/passwordSent.html"),name="password_reset_done"),
    path("reset/<uidb64>/<token>/",authViews.PasswordResetConfirmView.as_view(template_name="pages/passwordForm.html",success_url = reverse_lazy("account:password_reset_complete"),form_class=PasswordSetForm) ,name="password_reset_confirm"),
    path("reset/done/",authViews.PasswordResetCompleteView.as_view(template_name="pages/passwordDone.html"),name="password_reset_complete"),
    path("password_change/", authViews.PasswordChangeView.as_view(template_name="pages/passwordChange.html",form_class=PasswordFormUpdate,success_url = reverse_lazy("account:password_change_done")), name="password_change"),
    path("password_change/done/",authViews.PasswordChangeDoneView.as_view(template_name="pages/passwordChangeDone.html"),name="password_change_done"),
]

cart/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('',views.Cart.as_view(),name = "cart"),
    path('shipping/', views.Shipping.as_view(), name='shipping'),
    path('shipping/selectAdress/<slug:adressId>', views.SelectAdress.as_view(), name='selectAdress'),
    path('shipping/payment/', views.Payment.as_view(), name='payment'),
    path('shipping/payment/success/', TemplateView.as_view(template_name='pages/success.html'), name='success'),
    path('shipping/payment/cancel/', TemplateView.as_view(template_name='pages/cancel.html'), name='cancel'),
    path('shipping/payment/webHook/',views.WebHook.as_view(),name='webHook')
]

catalogue/urls.py
from django.urls import path
from . import views

app_name = "catalogue"

urlpatterns = [
    path('', views.Shop.as_view(),name = 'shop'),
    path('update-header', views.update_cart,name='updateHeader'),
    path('<int:pk>/',views.ProductView.as_view(), name='productDetail'),
    path('add-to-cart/<slug:productId>/',views.AddToCart.as_view(),name='addToCart'),
    path('delete-to-cart/<slug:orderItemId>/',views.DeleteToCart.as_view(),name='deleteToCart'),
    path('remove/<int:orderItemId>/',views.Remove.as_view(),name='remove'),
    path('buy/<int:orderItemId>/',views.BuyOrder.as_view(),name='buyOrder'),
    path('buy-all/',views.BuyAll.as_view(),name='buyAll'),
]
    
    

djangoEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'djangoEcommerce'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(),name = 'home'),
    path('home', views.Home.as_view(),name = 'home'),
    path('shop/',include('catalogue.urls')),
    path('account/',include('account.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

account/models.py
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    pass

account/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm,PasswordChangeForm, SetPasswordForm
from account.models import User
from django import forms


class UserFormLogin(AuthenticationForm):
    fields = '__all__'
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder']='Username'
        self.fields['username'].label = False
        self.fields['password'].widget.attrs['placeholder']='Password'
        self.fields['password'].label = False

class PasswordFormUpdate(PasswordChangeForm):
    fields = "__all__"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs['placeholder']='Old password'
        self.fields['old_password'].label = False
        self.fields['new_password1'].widget.attrs['placeholder']='New password'
        self.fields['new_password1'].label = False
        self.fields['new_password2'].widget.attrs['placeholder']='New password again'
        self.fields['new_password2'].label = False
        
class PasswordSetForm(SetPasswordForm):
    fields = "__all__"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].widget.attrs['placeholder']='New password'
        self.fields['new_password1'].label = False
        self.fields['new_password2'].widget.attrs['placeholder']='New password again'
        self.fields['new_password2'].label = False

class UserFormUpdate(forms.ModelForm):
    username = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ['username', 'email']
    def clean_email(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if email and User.objects.filter(email=email).exclude(username=self.instance.username).count():
            raise forms.ValidationError('This email address is already in use. Please supply a different email address.')
        return email
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder']='Username'
        self.fields['username'].label = False
        self.fields['email'].widget.attrs['placeholder']='Email'
        self.fields['email'].label = False

 


class UserFormSignUp(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username','email','password1','password2']
    def __init__(self, *args, **kwargs):
        print("################")
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder']='Username'
        self.fields['username'].label = False
        self.fields['email'].widget.attrs['placeholder']='Email'
        self.fields['email'].label = False
        self.fields['password1'].widget.attrs['placeholder']='Password'
        self.fields['password1'].label = False
        self.fields['password2'].widget.attrs['placeholder']='Password again'
        self.fields['password2'].label = False

cart/forms.py
from django import forms
from cart.models import Adress


class AdressForm(forms.ModelForm):
    class Meta:
        model = Adress
        fields = '__all__'
        exclude = ['user']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].widget = forms.TextInput(attrs={'placeholder': 'City'})
        self.fields['city'].label = False
        self.fields['zip_code'].widget = forms.TextInput(attrs={'placeholder':'Zip Code'}) 
        self.fields['zip_code'].label = False
        self.fields['address_line_1'].widget = forms.TextInput(attrs={'placeholder':'Adresse line'}) 
        self.fields['address_line_1'].label = False
        self.fields['address_line_2'].widget = forms.TextInput(attrs={'placeholder':'Adresse line complementary'}) 
        self.fields['address_line_2'].label = False

account/views.py
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import FormView, TemplateView, RedirectView, UpdateView
from cart.models import Order
from .forms import *
from django.contrib.auth.forms import PasswordChangeForm
from account.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

@method_decorator(login_required, name='dispatch')
class Logout(RedirectView):
    permanent = True
    pattern_name = 'home'
    def get_redirect_url(self, *args, **kwargs):
        logout(self.request)
        messages.success(self.request,"You are now logout")
        return super().get_redirect_url(*args, **kwargs)

class SignUpView(FormView):
    form_class = UserFormSignUp
    template_name = 'pages/sign-up.html'
    success_url = '/'

    def form_valid(self, form):
        form = login(request=self.request, user=form.save(commit=True))
        messages.success(self.request,"You're account was successfully created and you are login !!!")
        return super().form_valid(form)

@login_required
def UpdateUserView(request):
    if request.method == 'POST':
        form = UserFormUpdate(request.POST, instance=request.user)
        if form.is_valid():
            user_form = form.save()
            messages.success(self.request,"Your information has been updated")
            return redirect('account:account')
        else:
            return render(request, 'pages/updateUser.html',{'form':form})
    else:
        form = UserFormUpdate(instance=request.user)
        return render(request, 'pages/updateUser.html',{'form':form})

# class LoginView(FormView):
#     template_name = 'pages/login.html'
#     success_url = "/"
#     def form_valid(self, form):
#         login(request=self.request,user=form.user)
#         messages.success(self.request,"Hello, you are now login, happy to see you !")
#         return super().form_valid(form)

@method_decorator(login_required, name='dispatch')
class AccountView(TemplateView):
    template_name = 'pages/account.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['user'] = user
        context['previousOrder'] = Order.objects.filter(user=user,ordered=True)
        return context

cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from catalogue.decorators import order_required, adress_required
from .utils import get_or_set_order, refresh_quantity
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, FormView, RedirectView
from cart.forms import AdressForm
from cart.models import Order, Adress
import stripe
from django.contrib import messages
from decouple import config

class Cart(TemplateView):
    template_name = 'pages/cart.html'

@method_decorator(login_required(login_url="/account/login"), name='dispatch')
@method_decorator(order_required, name='dispatch')
class Shipping(FormView):
    form_class = AdressForm
    template_name = 'pages/shipping.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save(commit=True)
        messages.success(self.request,"You had successfully create a new address")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('cart:shipping')

@method_decorator(adress_required, name='dispatch')
@method_decorator(login_required(login_url='/account/login'), name='dispatch')
class Payment(TemplateView):
    template_name = 'pages/payment.html'
    def post(self, request, *args, **kwargs):
        try :
            stripe.api_key = config("STRIPE_KEY",default='sk_test_51KyVnpBtHPWEuLFwI33xUlMRcm2CY0WiFvtQt7D4tY8emMBAD0kK5s9aC0z1bN3c9bqAmBGVhPwWZN8KRbdeemRC00mxdVboJC',cast=str)
            YOUR_DOMAIN = config("DOMAINS",default="http://localhost:8000",cast=str)
            SUCCESS_URL_STRIPE = config("SUCCESS_URL_STRIPE",default="http://localhost:8000/cart/shipping/payment/success/",cast=str)
            FAIL_URL_STRIPE = config("FAIL_URL_STRIPE",default="http://localhost:8000/cart/shipping/payment/cancel/",cast=str)
            order = get_or_set_order(request)
            items = [{
                        'price_data': {
                            'currency': 'eur',
                            'unit_amount': x.product.price,
                            'product_data': {
                                'name': x.product.name,
                                'images': [x.product.img.url],
                            },
                        },
                        'quantity': x.quantity
                    } for x in order.orderItems.all()]
            checkout_session = stripe.checkout.Session.create(
                line_items=items,
                metadata={'order_id': order.id},
                mode='payment',
                payment_intent_data={
                    'capture_method': 'manual',
                },
                success_url=SUCCESS_URL_STRIPE,
                cancel_url=FAIL_URL_STRIPE,
            )
            order.payment_id = checkout_session.stripe_id
            order.save()
            return redirect(checkout_session.url)
        except Exception as e:
            print(str(e))
        return render(request,'pages/payment.html')


@method_decorator(csrf_exempt, name='dispatch')
class WebHook(View):
    def post(self,request):
        stripe.api_key = 'sk_test_51KyVnpBtHPWEuLFwI33xUlMRcm2CY0WiFvtQt7D4tY8emMBAD0kK5s9aC0z1bN3c9bqAmBGVhPwWZN8KRbdeemRC00mxdVboJC'
        print("enter")
        payload = request.body
        sig_header = request.META['HTTP_STRIPE_SIGNATURE']
        event = None
        endpoint_secret = 'whsec_0e2e2ebe8a26f6477ae77c01f467cabb1cccb6db0f344846cab5650b33f0e561'
        try:
            event = stripe.Webhook.construct_event(
                payload, sig_header, endpoint_secret
            )
        except ValueError as e:
            # Invalid payload
            return HttpResponse(status=400)
        except stripe.error.SignatureVerificationError as e:
            # Invalid signature
            return HttpResponse(status=400)

        print(event['type'])
        if event['type'] == 'checkout.session.completed':
            session = event['data']['object']
            order = Order.objects.get(id=session['metadata']['order_id'])
            if order.is_valid():
                paymentIntent_id = session['payment_intent']
                intent = stripe.PaymentIntent.capture(
                    paymentIntent_id
                )
                refresh_quantity(order)
            else :
                print("stock pas disponible")
                paymentIntent_id = session['payment_intent']
                intent = stripe.PaymentIntent.capture(
                    paymentIntent_id,0
                )
                return HttpResponse(status=400)
        return HttpResponse(status=200)



@method_decorator(login_required(login_url="/account/login/"), name='dispatch')
class SelectAdress(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        order = get_or_set_order(self.request)
        order.adress = Adress.objects.get(id=kwargs['adressId'])
        order.save()
        messages.success(self.request,"You choose a new address")
        return reverse('cart:shipping')

templates/pages/account.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/account.scss' %}" />
{% endblock %}

{% block content %}


<div class="account flex column align-center">
    <h1>My profile</h1>
    <h2>Who am I? Where am I? Why am I? Look no further for the answers. </h2>
    <div class="accountContainer flex column">
        <h2>My info</h2>
        <div>{{user.username}}</div>
        <div>{{user.email}}</div>
        <a style="margin-top:10px" href="{% url 'account:updateUser' %}">Change profil</a>
        <div class="flex row space-between">
            <a href="{% url 'account:password_change' %}">Change password</a>
            <a class="logout" href="{% url 'account:logout' %}">Logout</a>
        </div>
    </div>
</div>


{% endblock %}

{% comment %} {% for order in previousOrder %}
        {{order}}
        {% for orderItem in order.orderItems.all %}
            {{orderItem}}
        {% endfor %}
{% endfor %}
    {% if request.user.is_authenticated %}
        <li><a href="{% url 'account:logOut' %}">Log out</a></li>
    {% endif %} {% endcomment %}

templates/pages/cancel.html
{% extends 'base.html' %}

{% load static %}
{% load sass_tags %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/information.scss' %}" />
{% endblock %}

{% block content %}
    <div class="informationContainer flex row align-center justify-center">
        <div class="container">
            <h1>What happend ? I don't understand !!</h1>
            <h2>This order was sadly canceled !</h2>
            <a href="{% url 'home' %}">Return to home with us !</a>
        </div>
    </div>
{% endblock %}

templates/pages/cart.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}
{% load tagsBasics %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/cart.scss' %}" />
{% endblock %}


{% block content %}
<div class="cart">
    <div class="flex row">
        <div class="left">
            <h1>Your cart</h1>
            <div class="orders">
                {% for orderItem in order.orderItems.all %}

                    <div class="bigCard">
                        <div class="flex row ">
                            <img src="{{orderItem.product.img.url}}" alt="">
                            <div class="text flex column">
                                <h2>{{orderItem.product.name}}</h2>
                                <span>Quantity: {{orderItem.quantity}} </span>
                                <span>Comes with: Charging cable</span>
                                <div class="price">{{orderItem.product.price|price}}</div>
                            </div>
                            <button class="add button" onclick="location.href=`{% url 'catalogue:addToCart' productId=orderItem.product.id %}?next={% url 'cart:cart' %}`;">Add</button>
                            <button class="remove button" onclick="location.href=`{% url 'catalogue:remove' orderItemId=orderItem.id %}?next={% url 'cart:cart' %}`">Remove</button>
                        </div>
                        <div class="text-1 text-margin-1">Get protection</div>
                        <div class="text-1">Let's face it, choosing a protection plan usually sucks. That's why we're keeping it simple. </div>
                    </div>

                {% endfor %}
            </div>
        </div>
        <div class="right">
            <h1>Summary</h1>
            <div class="first">
                <div class="cardCheckout">
                    <div class="line flex row space-between">
                        <span>items</span>
                        <span>{{order.total_order_float}}€</span>
                    </div>
                    <div class="line flex row space-between">
                        <span>Total shipping</span>
                        <span>Free</span>
                    </div>
                    <div class="line flex row space-between">
                        <a>Quality Assurance Fee</a>
                        <span>0.00€</span>
                    </div>
                    <div class="transition"></div>
                    <div class="line total flex row space-between">
                        <h2>Cart total</h2>
                        <h2>{{order.total_order_float}}€</h2>
                    </div>
                    <button onclick="location.href=`{% url 'cart:shipping'  %}`;">Checkout</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/pages/login.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/login.scss' %}" />
{% endblock %}

{% block content %}
<div class="formContainer flex column align-center justify-center">
    <div class="flex column">
        <h1>Initiating retina scan. JK, who’s there? </h1>
        <h2>It’s me. I’m logging in. </h2>
    </div>
    <div class="form flex column">
        <form class="flex column" action="{% url 'account:login' %}" method="post">
            {% csrf_token %}
            {% include 'components/displayForm.html' with form=form %}
            <input class="button" type="submit" value="Beam me up">
            <a href="{% url 'account:signUp' %}">Sign up here ! </a>
            <a href="{% url 'account:password_reset' %}">Forget password ?</a>
        </form>
    </div>
</div>
{% endblock %}

templates/pages/passwordChange.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/passwordChange.scss' %}" />
{% endblock %}

{% block content %}
<div class="formContainer flex column align-center justify-center">
    <div class="flex column">
        <h1>Initiating brain scan. JK, Tell me your secret! </h1>
        <h2>Update your password.</h2>
    </div>
    <div class="form flex column">
        <form class="flex column" method="post">
            {% csrf_token %}
            {% include 'components/displayForm.html' with form=form %}
            <input class="button" type="submit" value="Update your password">
            <a href="{% url 'account:account' %}">Go back to your profile</a>
        </form>
    </div>
</div>
{% endblock %}

templates/pages/passwordDone.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/information.scss' %}" />
{% endblock %}

{% block content %}

<div class="informationContainer flex row align-center justify-center">
    <div class="container">
        <h1>Congratulation !!!</h1>
        <h2>Your password has been set. </h2>
        <h2>You may go ahead and log in now !</h2>
        <a href="{% url 'account:login' %}">It's here !</a>
    </div>
</div>
{% endblock %}

templates/pages/passwordReset.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}
{% load tagsBasics %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/form.scss' %}" />
{% endblock %}

{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'account:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

{% block content %}

<div class="formContainer flex column align-center justify-center">
    <div class="flex column">
        <h1>Forgotten your password?</h1>
        <h2>Enter your email address below, and we’ll email instructions for setting a new one.</h2>
    </div>
    <div class="form flex column">
        <form class="flex column" method="POST">
            {% csrf_token %}
            {% include 'components/displayForm.html' with form=form placeholder="Email" %}
            <input class="button" type="submit" value="Send">
        </form>
    </div>
</div>
{% endblock %}

templates/pages/passwordSent.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/information.scss' %}" />
{% endblock %}

{% block content %}

<div class="informationContainer flex row align-center justify-center">
    <div class="container">
        <h1>Half-Done !!!</h1>
        <h2>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</h2>
        <h2>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</h2>
        <a href="{% url 'home' %}">Return to home with us !</a>
    </div>
</div>

{% endblock %}

templates/pages/productDetail.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}
{% load tagsBasics %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/productDetail.scss' %}" />
{% endblock %}

{% block content %}
    <div class="paths flex row align-center">
        <a href="{% url 'home' %}" class="path flex row align-center">
            <span>Home</span>
            <img src="{% static 'assets/next.svg' %}" alt="">
        </a>
        <a href="{% url 'home' %}" class="path flex row align-center">
            <span>Path to</span>
            <img src="{% static 'assets/next.svg' %}" alt="">
        </a>
        <a href="{% url 'home' %}" class="path flex row align-center">
            <span>Edit</span>
            <img src="{% static 'assets/next.svg' %}" alt="">
        </a>
        <span>
            {{product.name}}
        </span>
    </div>
    <div class="product-detail flex row">
        <img class="poster" src="{{product.img.url}}" alt="">
        <div class="info flex column">
            <h1>{{product.name}}</h1>
            <div class="first flex row space-between align-center">
                <span>{{product.description}}</span>
                <h2>{{product.price|price}}</h2>
            </div>
            <div class="second flex row space-between">
                <img src="{% static 'assets/comment.svg' %}" alt="">
                <button onclick="location.href=`{% url 'catalogue:addToCart' productId=product.id %}?next={% url 'catalogue:productDetail' pk=product.id %}`;">Buy</button>
            </div>
            <div class="transition"></div>
            <div class="carriers flex row align-center">
                <img src="{% static 'assets/lock.svg' %}" alt="">
                <span>Works with <a href="">all carriers</a> </span>
            </div>
            <div class="transition"></div>
            <div class="image-block">
                <img src="{% static 'assets/shipping.svg' %}" alt="">
            </div>
            <div class="image-block">
                <img src="{% static 'assets/even-less.svg' %}" alt="">
            </div>
            <div class="image-block">
                <img src="{% static 'assets/payment.svg' %}" alt="">
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/shipping.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/shipping.scss' %}" />
{% endblock %}

{% block content %}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>


<div class="formContainer flex row">
    <div class="flex column">
        <h1>Initiating map scan. JK, where you want to be delivered? </h1>
        <h2>Create your adresse. </h2>
        <div class="form flex column">
            <form class="flex column" action="{% url 'cart:shipping' %}" method="POST">
                {% csrf_token %}
                {% include 'components/displayForm.html' with form=form %}
                <input class="button" type="submit" value="Create an adresses">
            </form>
        </div>
    </div>
    
    <div class="shipping">
        <h2>Select your adresse of delivery</h2>
        <div class="adresses">
            {% for adress in request.user.adresses.all %}
                <div class="adresse flex row align-center">
                    <span>{{adress}}</span>
                    <a href="{% url 'cart:selectAdress' adressId=adress.id %}">select</a>
                </div>
            {% endfor %}
        </div>
        <div class="selected">
            adresse selected : {{order.adress}}
        </div>
        <form action="{% url 'cart:payment' %}" method="POST">
            {% csrf_token %}
            <input class="button" type="submit" value="Checkout">
        </form>
</div>

{% endblock %}

templates/pages/shop.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/shop.scss' %}" />
{% endblock %}


{% block content %}

<div class="shop">
    <h1>Your search:</h1>
    <div class="products flex row wrap space-between">
        {% for product in products %}
            {% include 'components/cardProduct.html' with product=product %}
        {% endfor %}
    </div>

</div>

{% endblock %}

templates/pages/sign-up.html
{% extends 'base.html' %}

{% load static %}
{% load sass_tags %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/sign-up.scss' %}" />
{% endblock %}


{% block content %}

<div class="formContainer flex column align-center justify-center">
    <div class="flex column">
        <h1>Initiating retina scan. JK, who’s there? </h1>
        <h2>Open sesame. I’m signing up. </h2>
    </div>  
    <div class="form flex column">
        <form class="flex column" method="post">
            {% csrf_token %}
            {% include 'components/displayForm.html' with form=form %}
            <input class="button" type="submit" value="Create an account">
            <a href="{% url 'account:login' %}">Already register ?</a>
        </form>
    </div>
</div>

{% endblock %}

templates/pages/success.html
{% extends 'base.html' %}

{% load static %}
{% load sass_tags %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/information.scss' %}" />
{% endblock %}

{% block content %}
    <div class="informationContainer flex row align-center justify-center">
        <div class="container">
            <h1>Congratulation !!!</h1>
            <h2>You have succefully order your items !</h2>
            <a href="{% url 'home' %}">Return to home with us !</a>
        </div>
    </div>
{% endblock %}

templates/pages/updateUser.html
{% extends 'base.html' %}
{% load static %}
{% load sass_tags %}

{% block stylsheet %}
     <link rel="stylesheet" href="{% sass_src 'pages/updateUser.scss' %}" />
{% endblock %}

{% block content %}
<div class="formContainer flex column align-center justify-center">
    <div class="flex column">
        <h1>Initiating brain scan. JK, what to modify? </h1>
        <h2>Update your profile .</h2>
    </div>
    <div class="form flex column">
        <form class="flex column" method="POST">
            {% csrf_token %}
            {% include 'components/displayForm.html' with form=form %}
            <input class="button" type="submit" value="Update your profile">
        </form>
        <a href="{% url 'account:account' %}">Go back to your profile</a>
    </div>
</div>
{% endblock %}