cart/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('',views.Cart.as_view(),name = "cart"),
    path('shipping/', views.Shipping.as_view(), name='shipping'),
    path('shipping/selectAdress/<slug:adressId>', views.SelectAdress.as_view(), name='selectAdress'),
    path('shipping/payment/', views.Payment.as_view(), name='payment'),
    path('shipping/payment/success/', TemplateView.as_view(template_name='pages/success.html'), name='success'),
    path('shipping/payment/cancel/', TemplateView.as_view(template_name='pages/cancel.html'), name='cancel'),
    path('shipping/payment/webHook/',views.WebHook.as_view(),name='webHook')
]

catalogue/urls.py
from django.urls import path
from . import views

app_name = "catalogue"

urlpatterns = [
    path('', views.Shop.as_view(),name = 'shop'),
    path('update-header', views.update_cart,name='updateHeader'),
    path('<int:pk>/',views.ProductView.as_view(), name='productDetail'),
    path('add-to-cart/<slug:productId>/',views.AddToCart.as_view(),name='addToCart'),
    path('delete-to-cart/<slug:orderItemId>/',views.DeleteToCart.as_view(),name='deleteToCart'),
    path('remove/<int:orderItemId>/',views.Remove.as_view(),name='remove'),
    path('buy/<int:orderItemId>/',views.BuyOrder.as_view(),name='buyOrder'),
    path('buy-all/',views.BuyAll.as_view(),name='buyAll'),
]
    
    

djangoEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'djangoEcommerce'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(),name = 'home'),
    path('home', views.Home.as_view(),name = 'home'),
    path('shop/',include('catalogue.urls')),
    path('account/',include('account.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load sass_tags %}
{% load static %}
<html>
    <head>
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'assets/favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'assets/favicon/site.webmanifest' %}">
        <link rel="mask-icon" href="{% static 'assets/favicon/safari-pinned-tab.svg' %}" color="#2b5797">
        <meta name="msapplication-TileColor" content="#2b5797">
        <meta name="theme-color" content="#ffffff">
        <meta charset="utf-8" />
        <title>TataTitiToto.</title>
        <link rel="stylesheet" href="{% sass_src 'variables.scss' %}" />
        <link rel="stylesheet" href="{% sass_src 'base.scss' %}" />
        <link rel="stylesheet" href="{% sass_src 'footer.scss' %}" />
        <link rel="stylesheet" href="{% sass_src 'header.scss' %}" />
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/messages.js' %}" defer></script>
    {% block stylsheet %}
    {% endblock %}
    
</head>

    <body>
        <header>
            {% block header %}
                {% include 'header.html' %}
            {% endblock %}
        </header>
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <div {% if message.tags %} class="message flex row justify-center {{ message.tags }}"{% endif %}> 
                    <span>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}Attention: {% endif %}
                        {{ message }}
                    </span>
                    <div class="delete-message">
                        <img src="{% static 'assets/close.svg' %}" alt="">
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
        <section>
            {% block content %}
            {% endblock %}
        </section>
        <footer>
            {% block footer %}
                {% include 'footer.html' %}
            {% endblock %}
        </footer>
    </body>
</html>

templates/footer.html
{% block footer %}
{% load static %}

<div class="footer">
    <div class="container">
        <div class="first">
            <span>Hello! We're Back Market, the leading marketplace for renewed devices. Our mission? To fight e-waste by giving expertly restored devices a second life. </span>
        </div>
        <div class="second flex row space-between">
            <div class="flex column">
                <h2>About</h2>
                <ul>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                </ul>
            </div>
            <div class="flex column">
                <h2>About</h2>
                <ul>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                </ul>
            </div>
            <div class="flex column">
                <h2>About</h2>
                <ul>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                </ul>
            </div>
            <div class="flex column">
                <h2>About</h2>
                <ul>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                    <li>
                        <a href="">About us</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="transition"></div>
        <div class="infos flex row space-around">
            <img src="{% static 'assets/logo.png' %}" alt="">
            <div>This website is a Clone of Black Market made by <a href="mailto:lionel.arel@outlook.fr">Lionel AREL.<br/></a> Go check my <a href="https://www.lionel-arel.com" target="_blank">portfolio </a> and my <a  href="https://www.linkedin.com/in/lionel-arel-8a43881ba/"  target="_blank">linkedin.</a> </div>
        </div>
    </div>
</div>

{% endblock %}

templates/header.html
{% block header %}
{% load static %}
{% load active_link_tags %}
<nav class="flex row space-between align-center">
    <div class="first flex row align-center">
        <a href="{% url 'home' %}"><img class="logo" src="{% static 'assets/logo-bm.gif' %}"></a>
        <ul class="flex row space-around">
            <li><a href="{% url 'home' %}">About us</a></li>
            <li><a href="{% url 'catalogue:shop' %}">Trade-in</a></li>
            <li><a href="{% url 'catalogue:shop' %}">Help</a></li>
        </ul>
    </div>
    <form class="input" method="GET" action="{% url 'catalogue:shop' %}">
        <label for="search_text">
        </label>
            <input name="search_text" type="text" id="search_text" placeholder="Are you looking for an iPhone 11, MacBook, Samsung, ...">
        <label for="submit">
            <img class="search" src="{% static 'assets/search.svg' %}" alt="">
        </label>
        <input id="submit" type="submit" style="display:none">
    </form>
    <div class="second flex row align-center">
        <ul class="flex row align-center">
            <li>
                <a class="{% active_link 'account:account' %}" href="{% url 'account:account' %}"> 
                    <img class="person" src="{% static 'assets/person.svg' %}" alt="">
                </a>
            </li>
            <li>
                <a class="{% active_link 'cart:cart' %}" href="{% url 'cart:cart' %}"> 
                    <img class="cart-logo" src="{% static 'assets/cart.svg' %}" alt="">
                    {% if order and order.orderItems.count != 0 %}
                        <div class="notification__cart"></div>
                    {% endif  %}
                </a>
            </li>
        </ul>
    </div>
</nav>
<div class="categories flex row align-center">
    <a href="{% url 'catalogue:shop' %}" class="first flex row align-center">
        <img class="all" src="{% static 'assets/all.svg' %}" alt="">
        <div>All</div>
    </a>
    {% for categorie in categories %}
        <a href="{% url 'catalogue:shop' %}?categorie={{categorie.name}}" class="categorie">
            {{categorie.name}}
        </a>
    {% endfor %}
</div>
{% endblock %}